# Amira Project 640
# AmiraZIBEdition
# Generated by AmiraZIBEdition 6.4.0
remove -all
remove "colormap1-80.icol.am" "DataTree.am" "DataOpt.am" "Camera-Orbit" "LineRaycast" "Opt Plane" "DataDirectory_DataTree.am" "Local Axes"

# Create viewers
viewer setVertical 1

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

set hideNewModules 1
[ load ${SCRIPTDIR}/colormap1-80.icol.am ] setLabel "colormap1-80.icol.am"
"colormap1-80.icol.am" setIconPosition 0 0
"colormap1-80.icol.am" setNoRemoveAll 1
"colormap1-80.icol.am" fire
"colormap1-80.icol.am" setMinMax 1 80
"colormap1-80.icol.am" flags setValue 1
"colormap1-80.icol.am" shift setMinMax -1 1
"colormap1-80.icol.am" shift setButtons 0
"colormap1-80.icol.am" shift setEditButton 1
"colormap1-80.icol.am" shift setIncrement 0.133333
"colormap1-80.icol.am" shift setValue 0
"colormap1-80.icol.am" shift setSubMinMax -1 1
"colormap1-80.icol.am" scale setMinMax 0 1
"colormap1-80.icol.am" scale setButtons 0
"colormap1-80.icol.am" scale setEditButton 1
"colormap1-80.icol.am" scale setIncrement 0.1
"colormap1-80.icol.am" scale setValue 1
"colormap1-80.icol.am" scale setSubMinMax 0 1
"colormap1-80.icol.am" fire
"colormap1-80.icol.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/DataTree.am ] setLabel "DataTree.am"
"DataTree.am" setIconPosition 18 -2
"DataTree.am" fire
"DataTree.am" setTransform 1 1.07009e-06 3.27826e-07 0 -1.07009e-06 1 -9.7789e-08 0 -3.27826e-07 9.77887e-08 1 0 -2.15471e-05 -0.000100166 0 1
"DataTree.am" fire
"DataTree.am" setViewerMask 32767

set hideNewModules 0
[ load ${SCRIPTDIR}/DataOpt.am ] setLabel "DataOpt.am"
"DataOpt.am" setIconPosition 20 34
"DataOpt.am" fire
"DataOpt.am" fire
"DataOpt.am" setViewerMask 16383

set hideNewModules 0
create HxCircularCameraPath "Camera-Orbit"
"Camera-Orbit" setIconPosition 20 106
"Camera-Orbit" setVar "CustomHelp" {HxCircularCameraPath}
"Camera-Orbit" time setMinMax 0 360
"Camera-Orbit" time setSubMinMax 0 360
"Camera-Orbit" time setValue 0
"Camera-Orbit" time setDiscrete 0
"Camera-Orbit" time setIncrement 1
"Camera-Orbit" time animationMode -once
"Camera-Orbit" time setAnimationDelay 10
"Camera-Orbit" fire
"Camera-Orbit" action setOptValue 0 3
"Camera-Orbit" fire
"Camera-Orbit" setPosition 2.11395 1.90017 0.804633
"Camera-Orbit" setAimPoint 0.499999 0.499996 0.500002
"Camera-Orbit" setUpDirection -0.0891893 -0.112506 0.98964
"Camera-Orbit" setAxis 0 0 1
"Camera-Orbit" fire
"Camera-Orbit" setViewerMask 16383

set hideNewModules 0
create HxLineRaycast "LineRaycast"
"LineRaycast" setIconPosition 350 -2
"LineRaycast" setVar "CustomHelp" {HxLineRaycast}
"LineRaycast" data connect "DataTree.am"
"LineRaycast" lineColormap disconnect
"LineRaycast" lineColormap setDefaultColor 1 0.8 0.5
"LineRaycast" lineColormap setDefaultAlpha 0.500000
"LineRaycast" lineColormap activateLocalRange 1
"LineRaycast" lineColormap setLocalMinMax 0.000000 1.000000
"LineRaycast" lineColormap enableAlpha 1
"LineRaycast" lineColormap enableAlphaToggle 1
"LineRaycast" lineColormap setAutoAdjustRangeMode 1
"LineRaycast" lineColormap setColorbarMinMax 0 120
"LineRaycast" endingColormap connect "colormap1-80.icol.am"
"LineRaycast" endingColormap setDefaultColor 1 0.8 0.5
"LineRaycast" endingColormap setDefaultAlpha 0.500000
"LineRaycast" endingColormap activateLocalRange 1
"LineRaycast" endingColormap setLocalMinMax 1.000000 70.000000
"LineRaycast" endingColormap enableAlpha 1
"LineRaycast" endingColormap enableAlphaToggle 1
"LineRaycast" endingColormap setAutoAdjustRangeMode 1
"LineRaycast" endingColormap setColorbarMinMax 0 254
"LineRaycast" nodeColormap disconnect
"LineRaycast" nodeColormap setDefaultColor 1 0.8 0.5
"LineRaycast" nodeColormap setDefaultAlpha 0.500000
"LineRaycast" nodeColormap activateLocalRange 1
"LineRaycast" nodeColormap setLocalMinMax 0.000000 1.000000
"LineRaycast" nodeColormap enableAlpha 1
"LineRaycast" nodeColormap enableAlphaToggle 1
"LineRaycast" nodeColormap setAutoAdjustRangeMode 1
"LineRaycast" nodeColormap setColorbarMinMax 0 120
"LineRaycast" fire
"LineRaycast" display setValue 0 1
"LineRaycast" display setToggleVisible 0 1
"LineRaycast" display setValue 1 1
"LineRaycast" display setToggleVisible 1 1
"LineRaycast" display setValue 2 0
"LineRaycast" display setToggleVisible 2 1
"LineRaycast" lineRadius setState {item 0 0 }
"LineRaycast" lineRadiusScale setMinMax 0 1.22085297107697
"LineRaycast" lineRadiusScale setButtons 0
"LineRaycast" lineRadiusScale setEditButton 1
"LineRaycast" lineRadiusScale setIncrement 0.0813902
"LineRaycast" lineRadiusScale setValue 0.002
"LineRaycast" lineRadiusScale setSubMinMax 0 1.22085297107697
"LineRaycast" lineColor setState {item 0 1 item 1 1 }
"LineRaycast" lineConstColor setColor 0 1 1 1
"LineRaycast" lineOptions setState {item 0 1 item 1 1 }
"LineRaycast" lineBendAngle setMinMax 0 3.14159274101257
"LineRaycast" lineBendAngle setButtons 0
"LineRaycast" lineBendAngle setEditButton 1
"LineRaycast" lineBendAngle setIncrement 0.20944
"LineRaycast" lineBendAngle setValue 1.55966
"LineRaycast" lineBendAngle setSubMinMax 0 3.14159274101257
"LineRaycast" endingRadius setState {item 1 0 }
"LineRaycast" endingRadiusScale setMinMax 0 1.13067281246185
"LineRaycast" endingRadiusScale setButtons 0
"LineRaycast" endingRadiusScale setEditButton 1
"LineRaycast" endingRadiusScale setIncrement 0.0753782
"LineRaycast" endingRadiusScale setValue 0.01
"LineRaycast" endingRadiusScale setSubMinMax 0 1.13067281246185
"LineRaycast" endingColor setState {item 1 2 item 2 1 }
"LineRaycast" endingConstColor setColor 0 0.2 0.7 1
"LineRaycast" nodeRadius setState {item 0 0 }
"LineRaycast" nodeRadiusScale setMinMax 0 1.22085297107697
"LineRaycast" nodeRadiusScale setButtons 0
"LineRaycast" nodeRadiusScale setEditButton 1
"LineRaycast" nodeRadiusScale setIncrement 0.0813902
"LineRaycast" nodeRadiusScale setValue 0.305213
"LineRaycast" nodeRadiusScale setSubMinMax 0 1.22085297107697
"LineRaycast" nodeColor setState {item 1 0 item 0 1 item 2 1 }
"LineRaycast" nodeConstColor setColor 0 1 1 0.7
"LineRaycast" options setValue 0 1
"LineRaycast" options setToggleVisible 0 1
"LineRaycast" options setValue 1 0
"LineRaycast" options setToggleVisible 1 1
"LineRaycast" glowFunc setValue 0
"LineRaycast" glow setMinMax 0 5
"LineRaycast" glow setButtons 0
"LineRaycast" glow setEditButton 1
"LineRaycast" glow setIncrement 0.333333
"LineRaycast" glow setValue 2
"LineRaycast" glow setSubMinMax 0 5
"LineRaycast" selectedVertices 0
"LineRaycast" fire
"LineRaycast" setViewerMask 16383
"LineRaycast" setPickable 1

set hideNewModules 0
create HxBoundingBox "Opt Plane"
"Opt Plane" setIconPosition 347 79
"Opt Plane" setVar "CustomHelp" {HxBoundingBox}
"Opt Plane" data connect "DataOpt.am"
"Opt Plane" fire
"Opt Plane" options setState {item 0 1 color 1 0 0.838 0.165 item 3 1 }
"Opt Plane" lineWidth setMinMax 0 1 10
"Opt Plane" lineWidth setValue 0 3
"Opt Plane" font setState {name: "Arial Unicode MS" size: 12 buttonText: Select bold: 0 italic: 0 color: 0.8 0.8 0.8}
"Opt Plane" fire
"Opt Plane" setViewerMask 16383
"Opt Plane" setShadowStyle 0
"Opt Plane" setPickable 1

set hideNewModules 1
create HxDataDirectory "DataDirectory_DataTree.am"
"DataDirectory_DataTree.am" setIconPosition 0 0
"DataDirectory_DataTree.am" setInvisible 1
"DataDirectory_DataTree.am" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_DataTree.am" parentDir connect "Data"
"DataDirectory_DataTree.am" attachedData connect "DataTree.am"
"DataDirectory_DataTree.am" fire
"DataDirectory_DataTree.am" setViewerMask 16383

set hideNewModules 0
create HxAxis "Local Axes"
"Local Axes" setIconPosition 349 36
"Local Axes" setVar "CustomHelp" {HxAxis}
"Local Axes" data connect "DataTree.am"
"Local Axes" fire
"Local Axes" axis setValue 0 1
"Local Axes" axis setToggleVisible 0 1
"Local Axes" axis setValue 1 1
"Local Axes" axis setToggleVisible 1 1
"Local Axes" axis setValue 2 1
"Local Axes" axis setToggleVisible 2 1
"Local Axes" options setValue 0 1
"Local Axes" options setToggleVisible 0 1
"Local Axes" options setValue 1 0
"Local Axes" options setToggleVisible 1 1
"Local Axes" thickness setMinMax 1 15
"Local Axes" thickness setButtons 0
"Local Axes" thickness setEditButton 1
"Local Axes" thickness setIncrement 0.933333
"Local Axes" thickness setValue 5
"Local Axes" thickness setSubMinMax 1 15
"Local Axes" color setColor 0 1 0 0
"Local Axes" color setColor 1 0 1 0
"Local Axes" color setColor 2 0 0 1
"Local Axes" color setColor 3 1 0.8 0.5
"Local Axes" axisNames setState {text 1 x text 3 y text 5 z }
"Local Axes" textOnOff setValue 0
"Local Axes" font setState {name: "Arial Unicode MS" size: 10 buttonText: Select bold: 0 italic: 0 color: 0.8 0.8 0.8}
"Local Axes" fire
"Local Axes" setBoundingBox 0 1 0 1 0 1
"Local Axes" setDelta 0 
"Local Axes" setLocalMode 0 
"Local Axes" setFlip 0 0 
"Local Axes" setFlip 1 0 
"Local Axes" setFlip 2 0 
"Local Axes" fire
"Local Axes" setViewerMask 16383
"Local Axes" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.293884 0.622034 0.725746 2.5229
viewer 0 setCameraPosition 2.11395 1.90017 0.804633
viewer 0 setCameraFocalDistance 2.15827
viewer 0 setCameraNearDistance 1.22528
viewer 0 setCameraFarDistance 3.00192
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

##### Animations: begin #####
_animations removeAll
_animations create {
<!DOCTYPE NewAnimation>
<Settings createdFromDemoMaker="false" currentPlayMode="PLAY_MODE_ONCE" timeUpdateInterval="40" playSpeedFactor="1" currentTime="0" endTime="10000" startTime="0">
 <Options skipBreakEvents="false" skipPauseEvents="false" functionKeysActivated="true" skipGoToEvents="false" autoStartActivated="false" skipSnapshotEvents="false" snappingResolution="1000" snapshotsOutputDirectory="${AMIRAZIBEDITION_DATADIR}"/>
 <AnimationGroup name="All">
  <AnimationGroup name="Specific Events">
   <Animation name="Break"/>
   <Animation name="Waiting duration"/>
  </AnimationGroup>
  <AnimationGroup name="Camera-Orbit">
   <Animation name="Time: value">
    <Keyframe considerOnlyOneValue="true" leftValue="0" timeLocked="false" interpolationCurve="0" time="0" rightValue="0"/>
    <Keyframe considerOnlyOneValue="true" leftValue="360" timeLocked="false" interpolationCurve="0" time="10000" rightValue="360"/>
   </Animation>
  </AnimationGroup>
 </AnimationGroup>
</Settings>
}
_animations setCurrentAnimationDirector {NewAnimation}
##### Animations: end #####

correlationPanel closeTabs
correlationPanel setTabName 0 "Correlation 1"
correlationPanel 0 setLogScalingOnAxis 0 0
correlationPanel 0 setLogScalingOnAxis 1 0

histogramPanel closeTabs
histogramPanel setTabName 0 "Histogram 1"
histogramPanel 0 setLogScalingOnAxis 0 0
histogramPanel 0 setLogScalingOnAxis 1 1

DataTree.am show hit
DataTree.am fire
